function Hd = band_pass(Fs) % Fs为Sampling Frequency

%BAND_PASS Returns a discrete-time filter object.
% MATLAB Code
% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% All frequency values are in Hz.
 
Fstop1 = 500;         % First Stopband Frequency
Fpass1 = 680;         % First Passband Frequency
Fpass2 = 1500;        % Second Passband Frequency
Fstop2 = 1600;       % Second Stopband Frequency
Astop1 = 20;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 30;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly
 
% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);
end
% [EOF]